services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      - postgres
      - log_service
    env_file:
      - .env

  log_service:
    build: ./log_service
    container_name: log_service
    ports:
      - "${LOG_SERVICE_PORT}:${LOG_SERVICE_PORT}"
    depends_on:
      - postgres
    env_file:
      - .env
